### ISSUE TITLE
Does not resolve DomainEndpoint attribute of Elastic Search domain

### ISSUE THREAD

**Issue by esbenvb** [arabold/serverless-export-env#11]
While this plugin works for the names of my dynamoDb tables, I keep getthing this value for the HTTPS endpoint of my elastic search instance.

```json
    "searchIndexEndpoint": "[object Object]",
```
Here's how I define it:
```yml
Resources:
  SearchIndex:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: my-application
      ElasticsearchVersion: 6.3
...
```
```yml
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  environment:
    searchIndexEndpoint:
      Fn::GetAtt: [SearchIndex, DomainEndpoint]
...
```

**Comment by esbenvb** [comment]
Well I can see that `Fn:GetAtt` is already on the todo-list, and this seems to be a duplicate of #8, so I'm closing this ticket.

**Comment by esbenvb** [comment]
I temporarily solved it like this:

in `serverless.yml`

```yml
custom:
  searchIndexEndpoint:
    Fn::GetAtt: [SearchIndex, DomainEndpoint]

provider:
    searchIndexEndpoint: ${opt:searchIndexEndpoint, self:custom.searchIndexEndpoint}
```

Then I can do like this when I test locally.

`$ sls invoke local -f myFunction --path mocks/myFunction.json  --searchIndexEndpoint="some-url.es.amazonaws.com"`
