### ISSUE TITLE
sls invoke local =broken after serverless 1.35.0?

### ISSUE THREAD

**Issue by herebebogans** [arabold/serverless-export-env#12]
Anyone else noticing that the plugin seems to be broken with `sls invoke local -f <function>` after serverless 1.35.0

Ref: Environment variables resolve to [object Object] in the handler. Last serverless release that works is 1.34.1

This commit looks possibly the issue?

https://github.com/serverless/serverless/pull/5565/commits/44a6ac1a101a4ea8aee405bcd1ca538c1b1d88ce

**Comment by herebebogans** [comment]
Works again if I hack my local `serverless/lib/plugins/aws/invokeLocal/index.js` to revert the referenced commit.

@arabold not sure on the best way to fix the hook order?

**Comment by brucekaufman** [comment]
I've also run into this problem.  Any suggestions on how to fix?

**Comment by herebebogans** [comment]
@brucekaufman we've replicated the functionality of the plugin using stack exports to set environment variables in helper wrappers around serverless offline and serverless invoke.

You can then do a use "env variable or fallback to cloudformation ref" in serverless variables.

**Comment by brucekaufman** [comment]
@herebebogans can you provide an example of what you're talking about?  I am serverless newbie :)

**Comment by herebebogans** [comment]
No worries - I explained it poorly.

Here's an example of referencing a dynamo table with the pattern

```
custom:
  defaults:
    dynamo:
      myTable: !Ref MyTable

....
  dynamo:
    myTable: ${env:MY_TABLE, self:custom.defaults.dynamo.myTable}
.....
resources:
  Description: My Stack
  Resources:
    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
      AttributeDefinitions:
        - AttributeName: mykey
          AttributeType: S
      BillingMode: PAY_PER_REQUEST          
```
You then need something to set the MY_TABLE env variable before running sls offline or sls invoke We were using the aws cli along with direnv but now we have wrapper scripts for serverless offline / invoke using gulp.
