### ISSUE TITLE
file vars are not rendered

### ISSUE THREAD

**Issue by protoblade** [arabold/serverless-export-env#16]
It seems that the ```collectEnvVars()``` does not take into account file references and does not render them properly

Example
serverless.yml
```
provider:
  environment:
    testvalue: ${file(vars/${self:provider.stage}.json): testvalue
    stackName: teststring
```
generated .env
```
testvalue=${file(vars/dev.json):testvalue
stackName=teststring
```
