### ISSUE TITLE
Function environment variables with different values

### ISSUE THREAD

**Issue by coyoteecd** [arabold/serverless-export-env#17]
The plugin seems to assume that environment variable names are unique across all functions in the serverless.yml stack and lumps them together in a name=value list within .env file. This may or may not be the case in practice. 

Example serverless.yml:
```yml
plugins:
  - serverless-offline
  - serverless-export-env
[...]
functions:
  one-function:
    handler: src/one.handler
    environment:
      test: one

  other-function:
    handler: src/other.handler
    environment:
      test: other
```

With the plugin, invoking one-function shows process.env.test as `two`. Without the plugin, process.env.test is correctly set to `one`.
