### ISSUE TITLE
where do you put a variable that may cause a !Ref loop

### ISSUE THREAD

**Issue by MorCohenAres** [arabold/serverless-export-env#34]
Hi,
 
I think version 2.0 introduces a new bug.

It happens when you add an environment variable to a lambda function that is a reference to a circular structure.

For example, consider the following `serverless.yml`:
```
CognitoUserPool:
      Type: AWS::Cognito::UserPool
      ...
      Properties:
        LambdaConfig:
          # A function to run when a user complete his registration
          PostConfirmation: !GetAtt ConfirmUserLambdaFunction.Arn 

functions:
  confirmUser:
    ...
    environment:
      #  This variable can come from either function-level or global-level vars, and it causes a reference loop
      COGNITO_USER_POOL: !Ref CognitoUserPool
```

With this yml, when you run `sls deploy`, the following error occurs:
```
Circular dependency between resources: [Function, ...]
```

In version 1 I would simply put that variable inside the `Output` section. The alternative in version 2 is to put it on the global `provider.environment` section, which is not possible in this case since it causes the variable to be copied into all lambda functions (and thus causing the described problem)

One possible workaround is to create some "mock" function that is not a dependency of anything, and put the problematic variables there, then use `export-env --all` to collect this variable.
