### ISSUE TITLE
Getting `[Object object]` when trying to export function ARN

### ISSUE THREAD

**Issue by ezmiller** [arabold/serverless-export-env#49]
I am trying to export a function ARN that is defined in an environment variable on the provider environment:
```
provider:
  ...
  environment:
    BUILD_PRODUCT_FUNCTION_ARN: !GetAtt BuildProductLambdaFunction.Arn
```

The ARN is set correctly within the deployed environment, but the export `.env` reads:
```
BUILD_PRODUCT_FUNCTION_ARN=[object Object]
```
Is this a bug?
