### ISSUE TITLE
Help with migration from 1.x to 2.x

### ISSUE THREAD

**Issue by DavidNeiOs** [arabold/serverless-export-env#50]
Working with version 1 I was using the outputs to add some variables manually to the .env file like this:

```yaml
Outputs:
    AwsRegion:
      Value: ${self:custom.region}

    CognitoUserPoolId:
      Value: !Ref CognitoUserPool
```

this will output in V1.x
```
AWS_REGION=us-east-1
COGNITO_USER_POOL_ID=somevalue
```

I've tried manually adding them to `provider.environment` but running `!Ref` on provider (or custom) throws a circular dependency error also adding `AWS_REGION` to the provider throws an error as it is a reserved keyword.

I'm using these variables for testing
