### ISSUE TITLE
Support for serverless v3

### ISSUE THREAD

**Issue by pokryfka** [arabold/serverless-export-env#51]
Has the plugin been tested with [serverless v3](https://www.serverless.com/blog/serverless-framework-v3-is-live)?

I just updated to serverless v3 and noticed a few issues:

1.

environment values at function level are not exported, for example:

```
provider:
  environment:
    TEST1 = 1 # exported

functions:
  testFunc:
    environment:
       TEST2 = 2 # NOT exported
```

2. Outputs  are not exported, for example:

```
  - Outputs:
      AwsRegion:
        Value: ${self:custom.region} # NOT exported
```

3. Resolving of some properties does not work anymore, in my case:

- `!GetAtt RedisReplicationGroup.PrimaryEndPoint.Address`
- `!GetAtt GraphQlApi.GraphQLUrl`

stopped working, which is reported as:

```
Fn::GetAttResolvers not found in params file: RedisReplicationGroup.PrimaryEndPoint.Address
Fn::GetAttResolvers not found in params file: devGraphQlApi.GraphQLUrl
```
