### ISSUE TITLE
Disable the plugin for package/deploy and ny other non local invocation

### ISSUE THREAD

**Issue by spinlud** [arabold/serverless-export-env#59]
Is it possible to disable this plugin when calling `serverless package` or `serverless deploy`?

Tried with 
```yml
  export-env:
    enableOffline: true
    getAttMap:
      MyEnvVar: 'foobar'
```

but it is still try to resolve `MyEnvVar` even when calling `serverless deploy`. I would like the plugin to work only for local invocations like `serverless invoke local` or `serverless offline`. In all other cases I need the real thing with AWS CloudFormation variables resolver.
